-- 테이블 생성 SQL - MEMBER
CREATE TABLE MEMBER
(
    MEMBER_IDX    INT    NOT NULL,
    PRIMARY KEY (MEMBER_IDX)
);

-- Auto Increment를 위한 Sequence 추가 SQL - MEMBER.MEMBER_IDX
CREATE SEQUENCE MEMBER_SEQ
    START WITH 1
    INCREMENT BY 1;

-- Auto Increment를 위한 Trigger 추가 SQL - MEMBER.MEMBER_IDX
CREATE OR REPLACE TRIGGER MEMBER_AI_TRG
BEFORE INSERT ON MEMBER
REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
SELECT MEMBER_SEQ.NEXTVAL
INTO :NEW.MEMBER_IDX
FROM DUAL;
END;

-- DROP TRIGGER MEMBER_AI_TRG;

-- DROP SEQUENCE MEMBER_SEQ;

-- 컬럼 Comment 설정 SQL - MEMBER.MEMBER_IDX

COMMENT ON COLUMN MEMBER.MEMBER_IDX IS '멤버 인덱스';

-- -----------------------------------------------------------------------------

-- 테이블 생성 SQL - BOARD
CREATE TABLE BOARD
(
    BOARD_IDX      INT               NOT NULL,
    MEMBER_IDX     INT               NOT NULL,
    WRITER         VARCHAR2(20)      NOT NULL,
    TITLE          VARCHAR2(20)      NOT NULL,
    CONTENT        VARCHAR2(1000)    NOT NULL,
    HITS           INT               DEFAULT 0 NOT NULL,
    REGDATE        DATE              DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE    DATE              NULL,
    DELETE_DATE    DATE              NULL,
    PRIMARY KEY (BOARD_IDX)
);

-- Auto Increment를 위한 Sequence 추가 SQL - BOARD.BOARD_IDX
CREATE SEQUENCE BOARD_SEQ
    START WITH 1
    INCREMENT BY 1;

-- Auto Increment를 위한 Trigger 추가 SQL - BOARD.BOARD_IDX
CREATE OR REPLACE TRIGGER BOARD_AI_TRG
BEFORE INSERT ON BOARD
REFERENCING NEW AS NEW FOR EACH ROW
BEGIN
SELECT BOARD_SEQ.NEXTVAL
INTO :NEW.BOARD_IDX
FROM DUAL;
END;

-- DROP TRIGGER BOARD_AI_TRG;

-- DROP SEQUENCE BOARD_SEQ;

-- 테이블 Comment 설정 SQL - BOARD
COMMENT ON TABLE BOARD IS '게시글 테이블';

-- 컬럼 Comment 설정 SQL - BOARD.BOARD_IDX
COMMENT ON COLUMN BOARD.BOARD_IDX IS '게시글 인덱스';

-- 컬럼 Comment 설정 SQL - BOARD.MEMBER_IDX
COMMENT ON COLUMN BOARD.USER_IDX IS '유저 인덱스(유저 인덱스 참조 예정)';

-- 컬럼 Comment 설정 SQL - BOARD.WRITER
COMMENT ON COLUMN BOARD.WRITER IS '작성자';

-- 컬럼 Comment 설정 SQL - BOARD.TITLE
COMMENT ON COLUMN BOARD.TITLE IS '제목';

-- 컬럼 Comment 설정 SQL - BOARD.CONTENT
COMMENT ON COLUMN BOARD.CONTENT IS '내용';

-- 컬럼 Comment 설정 SQL - BOARD.HITS
COMMENT ON COLUMN BOARD.HITS IS '조회수';

-- 컬럼 Comment 설정 SQL - BOARD.REGDATE
COMMENT ON COLUMN BOARD.REGDATE IS '등록일자';

-- 컬럼 Comment 설정 SQL - BOARD.UPDATE_DATE
COMMENT ON COLUMN BOARD.UPDATE_DATE IS '수정일자';

-- 컬럼 Comment 설정 SQL - BOARD.DELETE_DATE
COMMENT ON COLUMN BOARD.DELETE_DATE IS '삭제일자';

-- Foreign Key 설정 SQL - BOARD(MEMBER_IDX) -> MEMBER(MEMBER_IDX)
ALTER TABLE BOARD
    ADD CONSTRAINT BOARD_FK FOREIGN KEY (USER_IDX)
        REFERENCES MEMBER (MEMBER_IDX) ;

-- Foreign Key 삭제 SQL - BOARD(MEMBER_IDX)
-- ALTER TABLE BOARD
-- DROP CONSTRAINT FK_BOARD_MEMBER_IDX_MEMBER_MEMBER_IDX;

